/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilities;

import Order.OrderAgent;
import jade.core.Agent;
import jade.wrapper.AgentController;
import jade.wrapper.StaleProxyException;

import javax.swing.*;

/**
 *
 * @author Ricardo Silva Peres <ricardo.peres@uninova.pt>
 */
public class ConsoleFrame extends javax.swing.JFrame {

    private Agent myAgent;
    private int orderCounter=1;

    private javax.swing.JComboBox<String> algorithmComboBox;
    private javax.swing.JComboBox<String> defectComboBox;
    private javax.swing.JCheckBox coppeliaCheckBox;
    
    /**
     * Creates new form ConsoleFrame
     */
    public ConsoleFrame(Agent a) {
        initComponents();
        this.myAgent = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jButtonLaunch = new javax.swing.JButton();
        typeAField = new javax.swing.JTextField();
        typeBField = new javax.swing.JTextField();
        typeCField = new javax.swing.JTextField();
        algorithmComboBox = new javax.swing.JComboBox<>();
        algorithmComboBox.setModel(new DefaultComboBoxModel<>(new String[] {"Cost + Distance", "Skill Matches"}));
        algorithmComboBox.setSelectedIndex(0);
        defectComboBox = new javax.swing.JComboBox<>();
        defectComboBox.setModel(new DefaultComboBoxModel<>(new String[] {"Repeat last skill", "Match defect location"}));
        defectComboBox.setSelectedIndex(0);
        coppeliaCheckBox = new javax.swing.JCheckBox();
        coppeliaCheckBox.setText("Coppelia cam?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SRCIM - Console Agent GUI");

        jButtonLaunch.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButtonLaunch.setText("Launch Order");
        jButtonLaunch.addActionListener(evt -> {
            try {
                launchButtonActionPerformed();
            } catch (StaleProxyException e) {
                throw new RuntimeException(e);
            }
        });

        jLabelA.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelA.setText("Product A");

        typeAField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typeAField.setText("0");

        jLabelB.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelB.setText("Product B");

        typeBField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typeBField.setText("0");

        jLabelC.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC.setText("Product C");

        typeCField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typeCField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelA)
                                        .addComponent(typeAField)
                                        .addComponent(jLabelB)
                                        .addComponent(typeBField)
                                        .addComponent(jLabelC)
                                        .addComponent(typeCField)
                                        .addComponent(algorithmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(defectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coppeliaCheckBox)
                                        .addComponent(jButtonLaunch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeAField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeBField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeCField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(algorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)     // <<< add (optional spacing)
                                .addComponent(defectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)     // <<< add (optional spacing)
                                .addComponent(coppeliaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLaunch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launchButtonActionPerformed() throws StaleProxyException {
        int productsA = Integer.parseInt(typeAField.getText());
        int productsB = Integer.parseInt(typeBField.getText());
        int productsC = Integer.parseInt(typeCField.getText());
        int algchoice = algorithmComboBox.getSelectedIndex() + 1;
        int defectchoice = defectComboBox.getSelectedIndex() + 1;
        boolean useCoppelia = coppeliaCheckBox.isSelected();
        launchOrder(productsA, productsB, productsC, algchoice, defectchoice, useCoppelia);
    }

    private void launchOrder(int a, int b, int c, int algchoice, int defectchoice, boolean useCoppelia) throws StaleProxyException {
        OrderAgent newOrder = new OrderAgent();
        newOrder.setArguments(new Object[]{a, b, c, algchoice, defectchoice, useCoppelia});
        String OrderId = "Order" + orderCounter;
        AgentController agent = this.myAgent.getContainerController().acceptNewAgent(OrderId, newOrder);
        agent.start();
        this.orderCounter++;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLaunch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JTextField typeAField;
    private javax.swing.JTextField typeBField;
    private javax.swing.JTextField typeCField;

}
